# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_marketingpreference_mailchimp_subscribed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingpreference',
            name='mailchimp_msg',
        ),
        migrations.RemoveField(
            model_name='marketingpreference',
            name='subscribed',
        ),
        migrations.RemoveField(
            model_name='marketingpreference',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='marketingpreference',
            name='updated',
        ),
    ]
