# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_auto_20181116_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreference',
            name='mailchimp_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketingpreference',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marketingpreference',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marketingpreference',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
